#!/bin/bash

quotes="/etc/update-motd.d/quotes.txt"
if [[ -f $quotes && $(( $RANDOM % 1 )) == 0 ]]; then
        random_line=$(shuf -i 1-$(wc -l < $quotes) -n 1)
        quote=$(sed -n -e "$random_line"p $quotes)
        DUE_DATE=$(echo $quote | cut -d"|" -f1)
        SELECTED_QUOTE=$(echo $quote | cut -d"|" -f2)
        if [[ -n $SELECTED_QUOTE && $(date +'%Y-%m-%d') < $(date -d $DUE_DATE +"%Y-%m-%d") ]]; then
                echo -e "\e[93mTip of the day:\e[39m $SELECTED_QUOTE\n"
        fi
fi